// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$0 from "./loaders/getGitHubCollaborators.ts";
import * as $$$1 from "./loaders/getGitHubStars.ts";
import * as $$$$$$0 from "./sections/BlogPosts.tsx";
import * as $$$$$$1 from "./sections/CardPreview/CardPreview.tsx";
import * as $$$$$$2 from "./sections/CardsList/CardsList.tsx";
import * as $$$$$$3 from "./sections/Faq.tsx";
import * as $$$$$$4 from "./sections/Header.tsx";
import * as $$$$$$14 from "./sections/hero-1.tsx";
import * as $$$$$$15 from "./sections/hero-2.tsx";
import * as $$$$$$5 from "./sections/Hero.tsx";
import * as $$$$$$16 from "./sections/hero2.tsx";
import * as $$$$$$6 from "./sections/ImageWithParagraph.tsx";
import * as $$$$$$7 from "./sections/Layout/Footer/Footer.tsx";
import * as $$$$$$8 from "./sections/Layout/Footer/Social.tsx";
import * as $$$$$$9 from "./sections/Logos.tsx";
import * as $$$$$$10 from "./sections/SectionPreview/SectionPreview.tsx";
import * as $$$$$$11 from "./sections/TabMenu/TabMenu.tsx";
import * as $$$$$$12 from "./sections/Testimonials.tsx";
import * as $$$$$$13 from "./sections/Theme/Theme.tsx";

const manifest = {
  "loaders": {
    "site/loaders/getGitHubCollaborators.ts": $$$0,
    "site/loaders/getGitHubStars.ts": $$$1,
  },
  "sections": {
    "site/sections/BlogPosts.tsx": $$$$$$0,
    "site/sections/CardPreview/CardPreview.tsx": $$$$$$1,
    "site/sections/CardsList/CardsList.tsx": $$$$$$2,
    "site/sections/Faq.tsx": $$$$$$3,
    "site/sections/Header.tsx": $$$$$$4,
    "site/sections/hero-1.tsx": $$$$$$14,
    "site/sections/hero-2.tsx": $$$$$$15,
    "site/sections/Hero.tsx": $$$$$$5,
    "site/sections/hero2.tsx": $$$$$$16,
    "site/sections/ImageWithParagraph.tsx": $$$$$$6,
    "site/sections/Layout/Footer/Footer.tsx": $$$$$$7,
    "site/sections/Layout/Footer/Social.tsx": $$$$$$8,
    "site/sections/Logos.tsx": $$$$$$9,
    "site/sections/SectionPreview/SectionPreview.tsx": $$$$$$10,
    "site/sections/TabMenu/TabMenu.tsx": $$$$$$11,
    "site/sections/Testimonials.tsx": $$$$$$12,
    "site/sections/Theme/Theme.tsx": $$$$$$13,
  },
  "apps": {
    "site/apps/decohub.ts": $$$$$$$$$$$0,
    "site/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
